language: node_js
node_js:
  - "lts/carbon"
dist: trusty
sudo: false
addons:
  chrome: stable
install:
    - npm install
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
  - npm run test:browser -- --browsers ChromeHeadlessNoSandbox
